name: 2b4cCore
main: twobeefourcee.core.Core
api-version: 1.13
version: 2.0.0
commands:
   update:
      default: op
   sethome:
      default: true
   home: 
      default: true
   delhome: 
      default: true
   joindate:
      aliases: ["jd"]
      default: true
   kill:
      aliases: ["suicide"]
      default: true
   dupe:
      default: true